#!/usr/bin/env sh
# Xelos Edge installer for macOS and Linux.
#
#   curl -fsSL https://raw.githubusercontent.com/markmelnic/xelos-edge/main/install.sh | sh
#
# What it does:
#   1. Verifies a Python 3.11+ interpreter is available.
#   2. Creates an isolated venv at ~/.xelos/runtime.
#   3. Installs the `xelos-edge` package into that venv.
#   4. Drops a thin `xelos` launcher into ~/.local/bin so it's on PATH.
#
# Re-running is safe: existing venvs are upgraded in place.

set -eu

XELOS_HOME="${XELOS_HOME:-$HOME/.xelos}"
RUNTIME_DIR="$XELOS_HOME/runtime"
BIN_DIR="${XELOS_BIN_DIR:-$HOME/.local/bin}"
PACKAGE_SPEC="${XELOS_PACKAGE_SPEC:-git+https://github.com/markmelnic/xelos-edge.git@main}"

# Pretty printing -----------------------------------------------------------
if [ -t 1 ] && command -v tput >/dev/null 2>&1 && [ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]; then
    BOLD=$(tput bold)
    DIM=$(tput dim)
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    RESET=$(tput sgr0)
else
    BOLD=""; DIM=""; RED=""; GREEN=""; YELLOW=""; RESET=""
fi

info()  { printf "%s==>%s %s\n" "$BOLD" "$RESET" "$1"; }
warn()  { printf "%s!!%s %s\n" "$YELLOW$BOLD" "$RESET" "$1" >&2; }
fail()  { printf "%sx%s %s\n" "$RED$BOLD" "$RESET" "$1" >&2; exit 1; }
ok()    { printf "%s✓%s %s\n" "$GREEN$BOLD" "$RESET" "$1"; }
note()  { printf "  %s%s%s\n" "$DIM" "$1" "$RESET"; }

# Find a usable Python ------------------------------------------------------
find_python() {
    for cmd in python3.13 python3.12 python3.11 python3 python; do
        if command -v "$cmd" >/dev/null 2>&1; then
            ver=$("$cmd" -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null || echo "")
            case "$ver" in
                3.11|3.12|3.13|3.14|3.15)
                    echo "$cmd"
                    return 0
                    ;;
            esac
        fi
    done
    return 1
}

suggest_python_install() {
    case "$(uname -s)" in
        Darwin)
            note "Install Python: brew install python@3.12"
            note "(Or get the official installer from https://www.python.org/downloads/)"
            ;;
        Linux)
            if   command -v apt    >/dev/null 2>&1; then note "sudo apt install python3 python3-venv"
            elif command -v dnf    >/dev/null 2>&1; then note "sudo dnf install python3"
            elif command -v pacman >/dev/null 2>&1; then note "sudo pacman -S python"
            elif command -v apk    >/dev/null 2>&1; then note "sudo apk add python3 py3-pip"
            else
                note "Install python 3.11+ using your distribution's package manager."
            fi
            ;;
        *)
            note "Install Python 3.11+ from https://www.python.org/downloads/"
            ;;
    esac
}

# Main ----------------------------------------------------------------------
info "Xelos Edge installer"

PYTHON=$(find_python || true)
if [ -z "${PYTHON:-}" ]; then
    warn "No Python 3.11+ on PATH."
    suggest_python_install
    fail "Install Python 3.11+ and re-run this script."
fi
ok "Found Python: $($PYTHON -V 2>&1) ($PYTHON)"

# Some Linux distros split out the venv stdlib package; check it works.
if ! "$PYTHON" -m venv --help >/dev/null 2>&1; then
    warn "Python is missing the 'venv' module."
    suggest_python_install
    fail "Install python3-venv (or equivalent) and re-run."
fi

mkdir -p "$XELOS_HOME"
chmod 700 "$XELOS_HOME" 2>/dev/null || true

if [ ! -d "$RUNTIME_DIR" ]; then
    info "Creating runtime venv at $RUNTIME_DIR"
    "$PYTHON" -m venv "$RUNTIME_DIR"
else
    info "Reusing runtime venv at $RUNTIME_DIR"
fi

info "Installing xelos-edge..."
VENV_PY="$RUNTIME_DIR/bin/python"

# Ensure pip is available in the venv (some Linux distros ship Python without
# ensurepip wired up by default — fall back to the bundled module, then to
# system pip3/pip targeting the venv as a last resort).
if ! "$VENV_PY" -m pip --version >/dev/null 2>&1; then
    if ! "$VENV_PY" -m ensurepip --upgrade >/dev/null 2>&1; then
        for sys_pip in pip3 pip; do
            if command -v "$sys_pip" >/dev/null 2>&1; then
                "$sys_pip" install --quiet --upgrade --target="$RUNTIME_DIR/lib" pip || true
                break
            fi
        done
    fi
fi

"$VENV_PY" -m pip install --quiet --upgrade pip
"$VENV_PY" -m pip install --quiet --upgrade "$PACKAGE_SPEC"
ok "Package installed"

# Drop launcher in ~/.local/bin --------------------------------------------
mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/xelos"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env sh
# Xelos Edge launcher (auto-generated by install.sh).
exec "$RUNTIME_DIR/bin/xelos" "\$@"
EOF
chmod +x "$LAUNCHER"
ok "Launcher: $LAUNCHER"

# PATH check ----------------------------------------------------------------
case ":$PATH:" in
    *":$BIN_DIR:"*)
        ;;
    *)
        warn "$BIN_DIR is not on your PATH yet."
        SHELL_NAME=$(basename "${SHELL:-}")
        case "$SHELL_NAME" in
            zsh)  RC="$HOME/.zshrc" ;;
            bash) RC="$HOME/.bashrc" ;;
            fish) RC="$HOME/.config/fish/config.fish" ;;
            *)    RC="" ;;
        esac
        if [ -n "$RC" ]; then
            note "Add this to $RC and reload your shell:"
            if [ "$SHELL_NAME" = "fish" ]; then
                note "    fish_add_path $BIN_DIR"
            else
                note "    export PATH=\"$BIN_DIR:\$PATH\""
            fi
        else
            note "Add $BIN_DIR to your PATH."
        fi
        ;;
esac

ok "Done."
printf "\nNext steps:\n"
note "1. Generate a pair code in the Xelos UI under Devices."
note "2. Run:  xelos pair <CODE>   (add --api <url> for staging / self-hosted)"
note "3. Then: xelos serve"
